baseurl = "https://www.keinemathematik.de/"
title = "Keine Mathematik"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "keinemathematik-de"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-156024236-2"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Do not omit raw html in markdown files
[markup.goldmark.renderer]
unsafe = true

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "red"
  description = "Blog für datenbasierte Fußballanalytik"
  copyright = "&copy;2020 Keine Mathematik"
  sidebarAbout = [
    "Blog für datenbasierte Fußballanalytik"
  ]

  email = "you@yoursite.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "Warum 'Keine Mathematik'?"
  url = "about/"

  [[params.navlinks]]
  name = "Datenquellen"
  url = "datenquellen/"

  [[params.navlinks]]
  name = "Tutorials"
  url = "tags/eventdaten/"

  [[params.navlinks]]
  name = "Autoren"
  url = "autoren/"

  [[params.navlinks]]
  name = "Mitmachen"
  url = "contact/"

  [params.social]
  twitter = "https://twitter.com/KeineMathematik"